Repository Dugout-Developers/CatchMate-SpringBoot, pull requests merged in 2025-01, with the labels that each got.

#38 [FEAT] 게시글 전체 조회시 필터 기능 구현
  build.gradle
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/global/config/QueryDslConfig.java
Labels: :sparkles:feature

#40 [FEAT] 상대방이 작성한 게시글 조회 기능 구현
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
Labels: :sparkles:feature

#42 [FEAT] 게시글 수정 API 기능 구현
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/game/entity/Game.java
  src/main/java/com/back/catchmate/domain/user/entity/User.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
Labels: :sparkles:feature

#43 [FEAT] 게시글 찜 생성, 삭제 기능 구현
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/converter/BookMarkConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/entity/BookMark.java
  src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/board/service/BookMarkService.java
  src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
  src/main/java/com/back/catchmate/domain/game/entity/Game.java
  src/main/java/com/back/catchmate/domain/user/entity/User.java
  src/main/java/com/back/catchmate/global/entity/BaseTimeEntity.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
Labels: :sparkles:feature

#45 [FEAT] 내가 찜한 게시글 조회 기능 구현
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/board/service/BookMarkService.java
  src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
Labels: :sparkles:feature

#50 fix : build 오류 수정
  src/main/java/com/back/catchmate/domain/game/converter/GameConverter.java
Labels: :bug:fix

#52 [FIX] 게시글 응답값 수정
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
Labels: :bug:fix

#53 [FEAT] 게시글 끌어올리기 API 기능 구현
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
Labels: :sparkles:feature

#56 [FIX] 회원가입시 응답값 수정
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/club/converter/ClubConverter.java
  src/main/java/com/back/catchmate/domain/club/service/ClubServiceImpl.java
  src/main/java/com/back/catchmate/domain/game/entity/Game.java
  src/main/java/com/back/catchmate/domain/game/repository/GameRepository.java
  src/main/java/com/back/catchmate/domain/notification/dto/NotificationResponse.java
  src/main/java/com/back/catchmate/domain/user/controller/UserController.java
  src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
  src/main/java/com/back/catchmate/global/auth/controller/AuthController.java
  src/main/java/com/back/catchmate/global/auth/converter/AuthConverter.java
  src/main/java/com/back/catchmate/global/auth/dto/AuthRequest.java
  src/main/java/com/back/catchmate/global/auth/dto/AuthResponse.java
  src/main/java/com/back/catchmate/global/auth/service/AuthService.java
  src/main/java/com/back/catchmate/global/auth/service/AuthServiceImpl.java
Labels: :bug:fix

#57 [REFACTOR] 게시글, 신청, 알림 삭제 기능 리팩토링
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/enroll/entity/Enroll.java
  src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
  src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
  src/main/java/com/back/catchmate/domain/notification/repository/NotificationRepository.java
  src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/back/catchmate/global/auth/converter/AuthConverter.java
  src/main/java/com/back/catchmate/global/auth/service/AuthServiceImpl.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
Labels: :zap:refactor

#60 [FIX] 게시글 작성, 찜하기 오류 수정
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
Labels: :bug:fix

#61 [FIX] 게시글 찜 삭제 오류 수정
  src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
Labels: :bug:fix

#63 [FIX] 임시 저장 게시글 조회 기능 수정
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
Labels: :bug:fix

#65 [FIX] 테이블명 수정
  src/main/java/com/back/catchmate/domain/board/entity/BookMark.java
Labels: :bug:fix

#67 [FIX] 게시글 임시 저장 로직 수정
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardRequest.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
Labels: :bug:fix

#69 [FIX] API 수정
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/enroll/converter/EnrollConverter.java
  src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
  src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
  src/main/java/com/back/catchmate/domain/notification/dto/NotificationResponse.java
  src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
  src/main/java/com/back/catchmate/domain/notification/service/NotificationService.java
  src/main/java/com/back/catchmate/domain/notification/service/NotificationServiceImpl.java
Labels: :bug:fix

#70 [FIX] 임시저장 로직 수정
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
Labels: :bug:fix

#71 [FIX] API 수정
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/board/service/BookMarkServiceImpl.java
Labels: :bug:fix

#72 [FIX] 게시글 상세 조회시 찜 여부 컬럼 추가
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
  src/main/java/com/back/catchmate/domain/board/repository/BookMarkRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardService.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
Labels: :bug:fix

#73 [FIX] 알림 응답값 수정
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
Labels: :bug:fix

#75 [FIX] API 요청 URL 변경 및 코드 가독성 리팩토링
  src/main/java/com/back/catchmate/domain/board/controller/BoardController.java
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/club/controller/ClubController.java
  src/main/java/com/back/catchmate/domain/club/service/ClubServiceImpl.java
  src/main/java/com/back/catchmate/domain/enroll/controller/EnrollController.java
  src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
  src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
  src/main/java/com/back/catchmate/domain/game/dto/GameResponse.java
  src/main/java/com/back/catchmate/domain/game/entity/Game.java
  src/main/java/com/back/catchmate/domain/notification/controller/NotificationController.java
  src/main/java/com/back/catchmate/domain/notification/converter/NotificationConverter.java
  src/main/java/com/back/catchmate/domain/notification/entity/Notification.java
  src/main/java/com/back/catchmate/domain/user/controller/UserController.java
  src/main/java/com/back/catchmate/domain/user/service/UserService.java
  src/main/java/com/back/catchmate/domain/user/service/UserServiceImpl.java
  src/main/java/com/back/catchmate/global/auth/dto/AuthRequest.java
  src/main/java/com/back/catchmate/global/config/AmazonConfig.java
  src/main/java/com/back/catchmate/global/config/QueryDslConfig.java
  src/main/java/com/back/catchmate/global/config/SecurityConfig.java
  src/main/java/com/back/catchmate/global/error/ErrorResponse.java
  src/main/java/com/back/catchmate/global/error/exception/BaseException.java
  src/main/java/com/back/catchmate/global/jwt/JwtValidateArgumentResolver.java
  src/main/java/com/back/catchmate/global/s3/S3Service.java
Labels: :bug:fix, :recycle:refactor

#76 [FIX] 게시글 응답값에 게시글 버튼 상태 컬럼 추가
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/dto/BoardResponse.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
Labels: :bug:fix

#77 [FIX] 임시 저장 게시글이 있을 경우에 게시글을 작성했을 경우, 해당 임시 저장 게시글 삭제 로직 추가
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
Labels: :bug:fix

#78 [FIX] API 수정
  src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
  src/main/java/com/back/catchmate/domain/notification/dto/FCMMessageRequest.java
  src/main/java/com/back/catchmate/domain/notification/service/FCMService.java
  src/main/java/com/back/catchmate/domain/user/converter/UserConverter.java
  src/main/java/com/back/catchmate/domain/user/dto/UserRequest.java
  src/main/java/com/back/catchmate/domain/user/entity/User.java
Labels: :bug:fix

#79 [FIX] PUSH 알림 메세지 수정
  src/main/java/com/back/catchmate/domain/notification/dto/FCMMessageRequest.java
  src/main/java/com/back/catchmate/domain/notification/service/FCMService.java
Labels: :bug:fix

#80 [FEAT] WebSocket 설정
  build.gradle
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
  src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
  src/main/java/com/back/catchmate/domain/chat/converter/ChatRoomConverter.java
  src/main/java/com/back/catchmate/domain/chat/converter/UserChatRoomConverter.java
  src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
  src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
  src/main/java/com/back/catchmate/domain/chat/entity/ChatMessage.java
  src/main/java/com/back/catchmate/domain/chat/entity/ChatRoom.java
  src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java
  src/main/java/com/back/catchmate/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/back/catchmate/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/back/catchmate/domain/chat/repository/UserChatRoomRepository.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatRoomService.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/back/catchmate/domain/game/entity/Game.java
  src/main/java/com/back/catchmate/domain/user/entity/User.java
  src/main/java/com/back/catchmate/global/config/LoggingAspect.java
  src/main/java/com/back/catchmate/global/config/MongodbConfig.java
  src/main/java/com/back/catchmate/global/config/WebSocketConfig.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
  src/main/java/com/back/catchmate/global/handler/StompHandler.java
Labels: :sparkles:feature

#81 [FIX] 채팅 요청 주소 변경
  src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
  src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/back/catchmate/global/config/SecurityConfig.java
Labels: :bug:fix

#82 [FEAT] 채팅방 생성 기능 구현 및 직관 신청 수락시 채팅방 입장 기능 구현
  src/main/java/com/back/catchmate/domain/board/converter/BoardConverter.java
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/board/repository/BoardRepository.java
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/chat/entity/UserChatRoom.java
  src/main/java/com/back/catchmate/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
  src/main/java/com/back/catchmate/global/error/ErrorCode.java
Labels: :sparkles:feature

#83 [FEAT] 내가 속한 채팅방 리스트 구현
  src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
  src/main/java/com/back/catchmate/domain/chat/converter/ChatRoomConverter.java
  src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
  src/main/java/com/back/catchmate/domain/chat/repository/UserChatRoomRepository.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/back/catchmate/domain/enroll/service/EnrollServiceImpl.java
Labels: :sparkles:feature

#84 [FEAT] 채팅 메세지 & 채팅방 리스트 조회 요청 주소 변경
  src/main/java/com/back/catchmate/domain/board/entity/Board.java
  src/main/java/com/back/catchmate/domain/chat/controller/ChatController.java
  src/main/java/com/back/catchmate/domain/chat/controller/ChatRoomController.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatRoomService.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatService.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
Labels: :bug:fix

#85 [FIX] 게시글 버튼 상태 확인 로직 수정
  src/main/java/com/back/catchmate/domain/board/service/BoardServiceImpl.java
  src/main/java/com/back/catchmate/domain/enroll/repository/EnrollRepository.java
Labels: :bug:fix

#87 [FIX] 채팅 전송시에 요청하는 필드값 수정
  src/main/java/com/back/catchmate/domain/chat/dto/ChatRequest.java
  src/main/java/com/back/catchmate/domain/chat/dto/ChatResponse.java
  src/main/java/com/back/catchmate/domain/chat/entity/ChatMessage.java
  src/main/java/com/back/catchmate/domain/chat/service/ChatServiceImpl.java
Labels: :bug:fix
